SimpleBlog/Blog.Web/Areas/Admin/Models/BlogCompose/BlogComposeBaseModel.cs
using Autofac;
using Blog.Framework.BlogCompose;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.Areas.Admin.Models.BlogCompose
{
    public class BlogComposeBaseModel : AdminBaseModel, IDisposable
    {
        protected IBlogComposeService  _blogComposeService;
        public BlogComposeBaseModel( IBlogComposeService  blogComposeService)
        {
            _blogComposeService = blogComposeService;
        }

        public BlogComposeBaseModel()
        {
            _blogComposeService = Startup.AutofacContainer.Resolve<IBlogComposeService >();
        }

        public void Dispose()
        {
            _blogComposeService?.Dispose();
        }
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Models/BlogCompose/BlogComposeModel.cs
using Blog.Framework.BlogCompose;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.Areas.Admin.Models.BlogCompose
{
    public class BlogComposeModel : BlogComposeBaseModel
    {
        public BlogComposeModel(IBlogComposeService  blogComposeService): base(blogComposeService)
        {

        }

        public BlogComposeModel() : base()
        {

        }

        internal object GetBlogCompose(DataTablesAjaxRequestModel dataTables)
        {
            var data = _blogComposeService.GetComposes(
                                   dataTables.PageIndex,
                                   dataTables.PageSize,
                                   dataTables.SearchText,
                                   dataTables.GetSortText(new string[] { "Title", "Body","CategoryId","ImageUrl","Date" }));
            return new
            {
                recordsTotal = data.total,
                recordsFiltered = data.totalDisplay,
                data = (from record in data.composes
                        select new string[]
                        {
                                record.Title,
                                record.Body,
                                record.CategoryId.ToString(),
                                record.ImageUrl,
                                record.Date.ToString("dd/mm/yyyy"),
                                record.Id.ToString()
                        }
                   ).ToArray()

            };
        }

        public IList<SelectListItem> GetCategoryList()
        {
            IList<SelectListItem> listItems = new List<SelectListItem>();

            foreach (var item in _blogComposeService.GetCategory())
            {
                var ctg = new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                };
                listItems.Add(ctg);
            }
            return listItems;
        }

        internal string Delete(int Id)
        {
            var deleteBlogCompose = _blogComposeService.DeleteCompose(Id);
            return deleteBlogCompose.Title;

        }
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Models/BlogCompose/CreateBlogComposeModel.cs
using Autofac;
using Blog.Framework.BlogCompose;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.Areas.Admin.Models.BlogCompose
{
    public class CreateBlogComposeModel : BlogComposeBaseModel
    {
        [Required]
        [StringLength (500 , MinimumLength = 3)]
        public string Title { get; set; }

        [Required]
        public string Body { get; set; }

        public string ImageUrl { get; set; }
        public IFormFile ImageFile { get; set; }
        public DateTime DateTime { get; set; } = DateTime.Now;
        public int CategoryId { get; set; }

        public CreateBlogComposeModel(IBlogComposeService  blogComposeService) : base(blogComposeService)
        {

        }

        public CreateBlogComposeModel() : base()
        {

        }

        public IList<SelectListItem> GetCategoryList()
        {
            IList<SelectListItem> listItems = new List<SelectListItem>();

            foreach (var item in _blogComposeService.GetCategory())
            {
                var ctg = new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                };
                listItems.Add(ctg);
            }
            return listItems;
        }
        public void Create()
        {
            var hostingEnvironment = Startup.AutofacContainer.Resolve<IWebHostEnvironment>();

            string wwwRootpath = hostingEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
            string extension = Path.GetExtension(ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            string path = Path.Combine(wwwRootpath + "/images/", fileName);

            var stream = new FileStream(path, FileMode.Create);
            ImageFile.CopyToAsync(stream);

            var blogCompose = new BlogComposes()
            {
                Title = this.Title,
                Body = this.Body,
                ImageUrl = fileName,
                Date =this.DateTime,
                CategoryId = this.CategoryId
            };

            _blogComposeService.CreateCompose(blogCompose);
        }
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Models/BlogCompose/EditBlogComposeModel.cs
using Autofac;
using Blog.Framework.BlogCompose;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.Areas.Admin.Models.BlogCompose
{
    public class EditBlogComposeModel : BlogComposeBaseModel
    {
        public int Id { get; set; }
        [Required]
        [StringLength(500, MinimumLength = 3)]
        public string Title { get; set; }

        [Required]
        public string Body { get; set; }

        public string ImageUrl { get; set; }
        public IFormFile ImageFile { get; set; }
        public DateTime DateTime { get; set; }
        public int CategoryId { get; set; }

        public EditBlogComposeModel(IBlogComposeService  blogComposeService) : base(blogComposeService)
        {

        }
        public EditBlogComposeModel() : base()
        {

        }

        public IList<SelectListItem> GetCategoryList()
        {
            IList<SelectListItem> listItems = new List<SelectListItem>();

            foreach (var item in _blogComposeService.GetCategory())
            {
                var ctg = new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                };
                listItems.Add(ctg);
            }
            return listItems;
        }

        public void Edit()
        {
            var hostingEnvironment = Startup.AutofacContainer.Resolve<IWebHostEnvironment>();

            string wwwRootpath = hostingEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
            string extension = Path.GetExtension(ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            string path = Path.Combine(wwwRootpath + "/images/", fileName);

            var stream = new FileStream(path, FileMode.Create);
            ImageFile.CopyToAsync(stream);

            var blogCompose = new BlogComposes()
            {
                Id = this.Id,
                Title = this.Title,
                Body = this.Body,
                ImageUrl = fileName,
                Date = DateTime.Now,
                CategoryId = this.CategoryId
            };

            _blogComposeService.EditCompose(blogCompose);
        }

        internal void Load( int id)
        {
            var blogCompose = _blogComposeService.GetCompose(id);

            if(blogCompose != null)
            {
                Id = blogCompose.Id;
                Title = blogCompose.Title;
                Body = blogCompose.Body;
                ImageUrl = blogCompose.ImageUrl;
                DateTime = blogCompose.Date;
                CategoryId = blogCompose.CategoryId;
            }
        }
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Controllers/BlogComposeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using Blog.Web.Areas.Admin.Models;
using Blog.Web.Areas.Admin.Models.BlogCompose;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Blog.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin,Administrator")]
    public class BlogComposeController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<BlogComposeModel> _logger;

        public BlogComposeController(IConfiguration configuration , ILogger<BlogComposeModel> logger)
        {
            _configuration = configuration;
            _logger = logger;
        }
        public IActionResult Index()
        {
            var model = Startup.AutofacContainer.Resolve<BlogComposeModel>();
            return View(model);
        }

        public IActionResult CreatePost()
        {
            var model = new CreateBlogComposeModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePost([Bind (nameof(CreateBlogComposeModel.Title),
                                               nameof(CreateBlogComposeModel.Body),
                                               nameof(CreateBlogComposeModel.ImageFile),
                                               nameof(CreateBlogComposeModel.CategoryId))] 
                                         CreateBlogComposeModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    model.Create();
                    model.Response = new ResponseModel("Blog Post Create Successful", ResponseType.Success);

                    //logger code
                    _logger.LogInformation("Blog Post Create Sucessfully");

                    return RedirectToAction("Index");
                }

                catch (Exception ex)
                {
                    model.Response = new ResponseModel("Blog Post failued.", ResponseType.Failure);
                    _logger.LogError($"BlogPost Create 'Failed'. Excption is : {ex.Message}");
                }
            }

            return View(model);
        }

        public IActionResult EditPost(int id)
        {
            var model = new EditBlogComposeModel();
            model.Load(id);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPost([Bind (nameof(EditBlogComposeModel.Id),
                                               nameof(EditBlogComposeModel.Title),
                                               nameof(EditBlogComposeModel.Body),
                                               nameof(EditBlogComposeModel.DateTime),
                                               nameof(EditBlogComposeModel.ImageFile),
                                               nameof(EditBlogComposeModel.CategoryId))]
                                         EditBlogComposeModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.Edit();
                    model.Response = new ResponseModel("Blog Post editing successful.", ResponseType.Success);

                    //logger code
                    _logger.LogInformation("Blog Post Edit Successfully");

                    return RedirectToAction("Index");

                }
                
                catch (Exception ex)
                {
                    model.Response = new ResponseModel("Blog Post Edit failued.", ResponseType.Failure);
                    // error logger code
                    _logger.LogError($"Blog Post Edit 'Failed'. Excption is : {ex.Message}");
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int id)
        {
            if (ModelState.IsValid)
            {
                var model = new BlogComposeModel();
                try
                {
                    var provider = model.Delete(id);
                    model.Response = new ResponseModel($"Post {provider} successfully deleted.", ResponseType.Success);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    model.Response = new ResponseModel("Post Delete failed.", ResponseType.Failure);
                    // error logger code
                    _logger.LogError($"Blog Post Delete 'Failed'. Excption is : {ex.Message}");
                }
            }
            return RedirectToAction("index");

        }

        public IActionResult GetPost()
        {
            var tableModel = new DataTablesAjaxRequestModel(Request);
            var model = Startup.AutofacContainer.Resolve<BlogComposeModel>();
            var data = model.GetBlogCompose(tableModel);
            return Json(data);
        }
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Framework;
using Blog.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Blog.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin,Administrator")]
    public class DashboardController : Controller
    {
       
        public IActionResult Index()
        {
            
            var model = new DashBoardModel();
            return View(model);

        } 
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Views/BlogCompose/CreatePost.cshtml
@model Blog.Web.Areas.Admin.Models.BlogCompose.CreateBlogComposeModel
    
<link href="~/lib/Trumbowyg-master/Trumbowyg-master/dist/ui/trumbowyg.min.css" rel="stylesheet" />

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>New Post</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">New Post</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Add a new Post</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <partial name="_ActionMessage" model="@Model.Response" />
                        <form asp-area="Admin" asp-controller="BlogCompose" asp-action="CreatePost" method="post" class="form-horizontal" enctype="multipart/form-data">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Title" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Title" class="form-control" />
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label asp-for="Body" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <textarea id="js-editor" asp-for="Body" class="form-control"> </textarea>
                                    <span asp-validation-for="Body" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="ImageName">Photo</label>
                                <input type="file" class="form-control" asp-for="ImageFile" placeholder="image/*">
                            </div>

                            <div class="form-group">
                                <label for="Category">Category</label>
                                <select asp-for="CategoryId" asp-items="@Model.GetCategoryList()" class="form-control">
                                    <option>Please select one</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-default" value="Submit" />
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section PageScripts
{
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/lib/Trumbowyg-master/Trumbowyg-master/dist/trumbowyg.min.js"></script>
    <script>
        $('#js-editor').trumbowyg();
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

SimpleBlog/Blog.Web/Areas/Admin/Views/BlogCompose/EditPost.cshtml
@model Blog.Web.Areas.Admin.Models.BlogCompose.EditBlogComposeModel

@{
    ViewData["Title"] = "Edit Post";
}
<link href="~/lib/Trumbowyg-master/Trumbowyg-master/dist/ui/trumbowyg.min.css" rel="stylesheet" />

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Home</a>
                        </li>
                        <li class="breadcrumb-item active">Update Post</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row justify-content-md-center">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Update Post</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <partial name="_ActionMessage" model="@Model.Response" />
                        <form asp-area="Admin" asp-controller="BlogCompose" asp-action="EditPost" method="post" class="form-horizontal" enctype="multipart/form-data">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <div class="form-group">
                                <label asp-for="Title" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Title" class="form-control" />
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label asp-for="Body" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <textarea id="js-editor" asp-for="Body" class="form-control"> </textarea>
                                    <span asp-validation-for="Body" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="ImageName">Photo</label>
                                <input  class="form-control" asp-for="ImageFile" placeholder="image/*" type="file">
                            </div>

                            <div class="form-group">
                                <label for="Category">Category</label>
                                <select asp-for="CategoryId" asp-items="@Model.GetCategoryList()" class="form-control">
                                    <option>Please select one</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-primary" value="Update" />
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section PageScripts
{
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/lib/Trumbowyg-master/Trumbowyg-master/dist/trumbowyg.min.js"></script>
    <script>
        $('#js-editor').trumbowyg();
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

SimpleBlog/Blog.Web/Areas/Admin/Views/BlogCompose/Index.cshtml
@model Blog.Web.Areas.Admin.Models.BlogCompose.BlogComposeModel

@section PageStyles
{
    <!-- DataTables -->
    <link rel="stylesheet" href="/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>DataTables</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <partial name="_ActionMessage" model="@Model.Response" />
                        <table id="Post" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Body</th>
                                    <th>CategoryId</th>
                                    <th>ImageUrl</th>
                                    <th>DateTime</th>
                                    <th>Action</th>

                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Title</th>
                                    <th>Body</th>
                                    <th>CategoryId</th>
                                    <th>ImageUrl</th>
                                    <th>DateTime</th>
                                    <th>Action</th>

                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure, you want to delete?</p>
                <form id="deleteForm" action="/admin/BlogCompose/DeletePost" method="post">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="deleteId" value="" name="id" />
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="deleteButton" class="btn btn-danger">Yes, Delete!</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@section PageScripts
{
    <!-- DataTables -->
    <script src="/admin/plugins/datatables/jquery.dataTables.js"></script>
    <script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $('#Post').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/Admin/BlogCompose/GetPost",
                "columnDefs": [
                    {

                        "orderable": false,
                        "targets": 3,
                        "render": function (data, type, row) {
                            var content = `<img src="/images/${data}" width="100" />`;
                            return content;
                        }
                    },

                    {
                        "orderable": false,
                        "targets": 5,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href='/admin/BlogCompose/EditPost/${data}'" value='${data}'>
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </button>
                                    <button type="submit" class="btn btn-danger btn-sm show-bs-modal" href="#" data-id='${data}' value='${data}'>
                                        <i class="fas fa-trash">
                                        </i>
                                        Delete
                                    </button>`;
                        }
                    }
                ]
            });

            $('#Post').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?')
                //$("#deleteForm").attr("action", "/admin/category/delete/" + id );
                $("#deleteId").val(id);
                modal.modal('show');
            });

            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });
        });
    </script>
}