SimpleBlog/Blog.Web/Areas/Admin/Models/Categories/CategoryBaseModel.cs
using Autofac;
using Blog.Framework.Categories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.Areas.Admin.Models.Categories
{
    public class CategoryBaseModel : AdminBaseModel, IDisposable
    {
        protected ICategoryService _categoryService;

        public CategoryBaseModel(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public CategoryBaseModel()
        {
            _categoryService = Startup.AutofacContainer.Resolve<ICategoryService>();
        }
        public void Dispose()
        {
            _categoryService?.Dispose();
        }
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Models/Categories/CategoryModel.cs
using Blog.Framework.Categories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.Areas.Admin.Models.Categories
{
    public class CategoryModel : CategoryBaseModel
    {
        public CategoryModel( ICategoryService categoryService)  : base ( categoryService) { }
        public CategoryModel()  : base () { }

        internal object GetCategory(DataTablesAjaxRequestModel dataTables)
        {
            var data = _categoryService.GetCategories(
                                    dataTables.PageIndex,
                                    dataTables.PageSize,
                                    dataTables.SearchText,
                                    dataTables.GetSortText(new string[] { "Id", "Name" }));
            return new
            {
                recordsTotal = data.total,
                recordsFiltered = data.totalDisplay,
                data = (from record in data.categories
                        select new string[]
                        {
                                record.Name,
                                record.Id.ToString()
                        }
                   ).ToArray()

            };
        }
        internal string Delete (int Id)
        {
            var deleteCategory = _categoryService.DeleteCategory(Id);
            return deleteCategory.Name;

        }
        
    }
        
    
}

SimpleBlog/Blog.Web/Areas/Admin/Models/Categories/CreateCategoryModel.cs
using Blog.Framework.Categories;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.Areas.Admin.Models.Categories
{
    public class CreateCategoryModel : CategoryBaseModel
    {
        [StringLength(150, MinimumLength = 3)]
        [Required]
        public string Name { get; set; }
        public CreateCategoryModel( ICategoryService categoryService) : base(categoryService)
        {

        }

        public CreateCategoryModel() : base()
        {

        }

        public void Create()
        {
            var category = new Category
            {
                Name = this.Name
            };

            _categoryService.CreateCategory(category);
        }
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Models/Categories/EditCategoryModel.cs
using Blog.Framework.Categories;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.Areas.Admin.Models.Categories
{
    public class EditCategoryModel : CategoryBaseModel
    {
        public int Id { get; set; }

        [StringLength(150, MinimumLength = 3)]
        [Required]
        public string Name { get; set; }

        public EditCategoryModel( ICategoryService categoryService) : base(categoryService)
        {

        }

        public EditCategoryModel() : base()
        {

        }

        public void Edit()
        {
            var category = new Category
            {
                Id = this.Id,
                Name = this.Name
            };

            _categoryService.EditCategory(category);
        }

        internal void Load(int id)
        {
            var category = _categoryService.GetCategory(id);
            if (category != null)
            {
                Id = category.Id;
                Name = category.Name;
            }
        }
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using Blog.Framework;
using Blog.Web.Areas.Admin.Models;
using Blog.Web.Areas.Admin.Models.Categories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Blog.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin,Administrator")]
    public class CategoryController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<CategoryModel> _logger;

        public CategoryController( IConfiguration configuration , 
                                   ILogger<CategoryModel> logger)
        {
            _configuration = configuration;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var model = Startup.AutofacContainer.Resolve<CategoryModel>();
            return View(model);
        }

        public IActionResult CreateCategory()
        {
            var model = new CreateCategoryModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCategory([Bind(nameof(CreateCategoryModel.Name))] 
        CreateCategoryModel model )
            
        {
            if(ModelState.IsValid)
            {
                try
                {
                    model.Create();
                    model.Response = new ResponseModel("Category Create Successful", ResponseType.Success);
                   
                    //logger code
                    _logger.LogInformation("Category Create Sucessfully");

                    return RedirectToAction("Index");
                }

                catch (DuplicationException ex)
                {
                    model.Response = new ResponseModel(ex.Message, ResponseType.Failure);
                    _logger.LogError("Category Name already Exist");
                }

                catch (Exception ex)
                {
                    model.Response = new ResponseModel("Category creation failued.", ResponseType.Failure);
                    _logger.LogError($"Category Create 'Failed'. Excption is : {ex.Message}");
                }
            }

            return View(model);
        }

        public IActionResult EditCategory(int id)
        {
            var model = new EditCategoryModel();
            model.Load(id);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCategory([Bind(nameof(EditCategoryModel.Id),
                                                nameof(EditCategoryModel.Name))]
                                            EditCategoryModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    model.Edit();
                    model.Response = new ResponseModel("Category editing successful.", ResponseType.Success);
                    
                    //logger code
                    _logger.LogInformation("Category Edit Successful");
                   
                    return RedirectToAction("Index");
                    
                }
                catch (DuplicationException ex)
                {
                    model.Response = new ResponseModel(ex.Message, ResponseType.Failure);

                    // error logger code
                    _logger.LogError($"Category Name Already Exist so Edit 'Failed'. Excption is : {ex.Message}");
                }
                catch (Exception ex)
                {
                    model.Response = new ResponseModel("Category Edit Failued.", ResponseType.Failure);
                    // error logger code
                    _logger.LogError( $"Category Edit 'Failed'. Excption is : {ex.Message}");
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCategory(int id)
        {
            if (ModelState.IsValid)
            {
                var model = new CategoryModel();
                try
                {
                    var provider = model.Delete(id);
                    model.Response = new ResponseModel($"Category {provider} successfully deleted.", ResponseType.Success);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    model.Response = new ResponseModel("Category Delete failed.", ResponseType.Failure);
                    // error logger code
                    _logger.LogError($"Category Delete 'Failed'. Excption is : {ex.Message}");
                }
            }
            return RedirectToAction("index");

        }

       
        public IActionResult GetCategory()
        {
            var tableModel = new DataTablesAjaxRequestModel(Request);
            var model = Startup.AutofacContainer.Resolve<CategoryModel>();
            var data = model.GetCategory(tableModel);
            return Json(data);
        }
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Framework;
using Blog.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Blog.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin,Administrator")]
    public class DashboardController : Controller
    {
       
        public IActionResult Index()
        {
            
            var model = new DashBoardModel();
            return View(model);

        } 
    }
}

SimpleBlog/Blog.Web/Areas/Admin/Views/Category/CreateCategory.cshtml
@model Blog.Web.Areas.Admin.Models.Categories.CreateCategoryModel

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>New Category</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">New Book</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Add a new Category</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <partial name="_ActionMessage" model="@Model.Response" />
                        <form asp-area="Admin" asp-controller="Category" asp-action="CreateCategory" method="post" class="form-horizontal">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Name" class="col-md-2 control-label"></label>
                                <div class="col-md-10">
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-default" value="Submit" />
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section PageScripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

SimpleBlog/Blog.Web/Areas/Admin/Views/Category/EditCategory.cshtml
@model Blog.Web.Areas.Admin.Models.Categories.EditCategoryModel

@{
    ViewData["Title"] = "Edit Category";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Home</a>
                        </li>
                        <li class="breadcrumb-item active">Update Group</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row justify-content-md-center">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Update Category</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <partial name="_ActionMessage" model="@Model.Response" />
                        <form asp-area="Admin" asp-controller="Category" asp-action="EditCategory" method="post" class="form-horizontal">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <div class="form-group">
                                <label asp-for="Name" class="col-md-2 control-label">Category Name</label>
                                <div class="col-md-10">
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-primary" value="Update" />
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section PageScripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

SimpleBlog/Blog.Web/Areas/Admin/Views/Category/Index.cshtml
@model Blog.Web.Areas.Admin.Models.Categories.CategoryModel

@section PageStyles
{
    <!-- DataTables -->
    <link rel="stylesheet" href="/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>DataTables</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <partial name="_ActionMessage" model="@Model.Response" />
                        <table id="Category" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Action</th>

                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Name</th>
                                    <th>Action</th>

                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure, you want to delete?</p>
                <form id="deleteForm" action="/admin/Category/DeleteCategory" method="post">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="deleteId" value="" name="id" />
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="deleteButton" class="btn btn-danger">Yes, Delete!</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@section PageScripts
{
    <!-- DataTables -->
    <script src="/admin/plugins/datatables/jquery.dataTables.js"></script>
    <script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $('#Category').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/Admin/Category/GetCategory",
                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 1,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href='/admin/Category/EditCategory/${data}'" value='${data}'>
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </button>
                                    <button type="submit" class="btn btn-danger btn-sm show-bs-modal" href="#" data-id='${data}' value='${data}'>
                                        <i class="fas fa-trash">
                                        </i>
                                        Delete
                                    </button>`;
                        }
                    }
                ]
            });

            $('#Category').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?')
                //$("#deleteForm").attr("action", "/admin/category/delete/" + id );
                $("#deleteId").val(id);
                modal.modal('show');
            });

            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });
        });
    </script>
}